### ISSUE TITLE
Unity crashes when custom ICE servers can't authenticate (invalid ICE credentials)

### ISSUE THREAD

**Issue by HugoKampsSB** [microsoft/MixedReality-WebRTC#122]
Hi!

I've been setting up my own RTC connection client, so I can connect from my browser with someone in Unity/the HoloLens. For this I've also set up my own TURN/STUN server using coturn on Ubuntu. When setting these STUN/TURN settings in the PeerConnection component in Unity, I forgot to enter the credentials at first, and this led to my Unity crashing when pressing the play button. I believe this should just result in an exception, and that it would be good to notify you of this!

I've included the error log for clarification :)
[error.log](https://github.com/microsoft/MixedReality-WebRTC/files/3824061/error.log)

Kind regards,
Hugo

**Comment by djee-ms** [comment]
I will have a look, thanks for the stack traces!

**Comment by djee-ms** [comment]
The callstack seems to be corrupted because `mrsPeerConnectionCreate()` never calls anything related to data channels. However any failure in creating the peer connection implementation will return a NULL pointer, which is dereferenced without a check. I fixed that in c3e110707cda0c13b76e7045960125df51bd8d0f and I assume should fix the crash you saw in Unity. I don't have a simple way to repro though at the moment. Feel free to try it out and let me know.

**Comment by HugoKampsSB** [comment]
Thanks for the quick response! I've tested the latest version of WebRTC (1.0.1) but it still occurs on my side. 

**Cause**
What I did to produce this error:
My PeerConnectionComponent contains 3 Ice servers. I've setup my own Coturn server on an Ubuntu droplet using DigitalOcean. This coturn server provides me with both TURN and STUN. 

IceServers[0]
type = stun
uri = {uri}:443

IceServers[1]
type = turn
uri = {uri}:443?transport=tcp

IceServers[2]
type = turn
uri = {uri}:443?transport=udp

To produce this I've emptied the Ice Username and Ice Credential. When pressing play I got the Unity crash. Afterwards I tried again but with the correct Username and Credential and then it worked.

**Crash information**

![image](https://user-images.githubusercontent.com/37140671/68576608-b05cb200-046e-11ea-8402-fef4b15779c4.png)
(screenshot from crash.dmp, I sadly cannot upload all crash information due to some filenames/folder names containing private information)

[error.log](https://github.com/microsoft/MixedReality-WebRTC/files/3830644/error.log)

**Comment by eirikhollis** [comment]
Tested the same thing with my solution, since I have a Kurento server running with both TURN and STUN, and can verify that commenting out `TurnUserName` and `TurnPassword` does indeed crash Unity.

**Comment by djee-ms** [comment]
The callstack is again garbled (`mrsPeerConnectionCreate()` cannot call `DataChannel::Send()`), so doesn't provide much information. I should be able to debug that later in the week or so.

**Comment by fibann** [comment]
@HugoKampsSB @eirikhollis I tried this on latest master, I added dummy TURN servers to the list and left username/password empty. The PeerConnection initialization failed (with `(iceserverparsing.cc:234): TURN URL without username, or password empty` in the debug logs), and I got an exception logged in Unity, but no crash. I haven't tried setting up a real TURN server, but I suspect this makes no difference as the initialization fails before even pinging the server.

Looking at #387 too I believe that in 1.0.x we used to crash if the PeerConnection initialization failed, but this has been fixed since. Can you verify that you don't get a crash on latest master or with 2.0 packages?

**Comment by eirikhollis** [comment]
@fibann Tested now in Unity 2019.4.5 with latest master as of yesterday, and it did not crash. Instead, I got a System.Exception on `PeerConnection.InitializeAsync(config, token)`, which is much, much better! Thanks for the work 👍
